### ISSUE TITLE
Direct Link Downloading not working with aria2c

### ISSUE THREAD

**Issue by Altafshah10** [Nubuki-all/Enc#12]
When using leech command

**Comment by Nubuki-all** [comment]
Drop logs my dude 
Sorry for the late reply

**Comment by Altafshah10** [comment]
![Screenshot_2024-06-04-07-00-01-44_0b342c26d6c44f3c8d2de40eabb4e1da](https://github.com/Nubuki-all/Enc/assets/117189106/993c8ba2-e1d4-4d8b-826a-8ea5d2f2e5b9)

No Error in logs

**Comment by Altafshah10** [comment]
[Logs.txt](https://github.com/user-attachments/files/15541383/Logs.txt)

**Comment by Altafshah10** [comment]
![IMG_20240604_070505_373](https://github.com/Nubuki-all/Enc/assets/117189106/6d12fba5-b2e4-4451-9541-28c0f676b09c)

With Download command it is working fine.

**Comment by Nubuki-all** [comment]
Should work now.
TY for reporting.
