### ISSUE TITLE
Add vps deployment comments 

### ISSUE THREAD

**Issue by narutobotx** [Nubuki-all/Enc#14]

**Comment by Nubuki-all** [comment]
Err you mean I should update the readme on how to deploy on vps?

**Comment by Ashwinking11** [comment]
Yes

**Comment by Ashwinking11** [comment]
> Err you mean I should update the readme on how to deploy on vps?

Yes add

**Comment by Nubuki-all** [comment]
@Ashwinking11 If that's all I'll close this issue.
Thanks.
