### ISSUE TITLE
Update ffmpeg -vf not working 

### ISSUE THREAD

**Issue by mksbil** [Nubuki-all/Enc#20]

**Comment by Nubuki-all** [comment]
Please provide more information or I'll close 🙂 
And this looks like an ffmpeg issue (if it is, I'm sorry I can't help you)

**Comment by narutobotx** [comment]
I trying to add -vf "drawtext=fontfile=font.ttf:fontsize=25:fontcolor=white:bordercolor=black@0.50:x=w-tw-10:y=10:box=1:boxcolor=black@0.5:boxborderw=6:text=hi"
But Ffmpeg error

**Comment by Nubuki-all** [comment]
make sure your {} is in triple quotes
So """{}"""

**Comment by mksbil** [comment]
Yes not working

**Comment by Nubuki-all** [comment]
Can you upload ffmpeg error?

**Comment by mksbil** [comment]
It's not working
