### ISSUE TITLE
Add video+audio merge feature 

### ISSUE THREAD

**Issue by mksbil** [Nubuki-all/Enc#22]

**Comment by Nubuki-all** [comment]
Kindly provide additional information on the feature.

**Comment by mksbil** [comment]
✶ Merger 1 : In this Function, All existing audio track will be replaced. And will be added your sent Audio (Single Audio).

✶ Merger 2 : In this Function, Your sent Audio track will be Merged, WITHOUT Replacing Existing Audio Tracks and Subtitles (Multi Audio & Subtitles)

✶ Click the Button of your choice 

Add like this bro

**Comment by Nubuki-all** [comment]
You can already do this with /mux command 
Simply reply to the video  with /mux add the ffmpeg parameters to replace or add the audio without the "ffmpeg"  and depending on where the audio is;
  - if it's in a local directory add -i {path/to/audio} in the parameters (The usual for when adding another input file in ffmpeg)
  - if it's already in tg forward it to a group and get the telegram link (the bot must also be in the same group) then add a new line (by pressing enter) after the params then -i {tg_link}
  - for direct link to audio use -i like the above
  Note: the newline before the -i is important or bot will interpret as a ffmpeg command 

Do /mux --help for more uses

**Comment by mksbil** [comment]
Send sample comment

**Comment by Nubuki-all** [comment]
Sure why not?

```
/mux -map 0:v -map 0:a -map 0:s -map 0:t -map 1:a -codec copy
-i https://t.me/c/0123456789/1234
```
To merge an audio of tg link with the replied video while keeping the original audio too

**Comment by mksbil** [comment]
Thanks bro it's working

**Comment by Nubuki-all** [comment]
Okay, I'm closing now 
Feel free to re-open if you still have any queries.
