### ISSUE TITLE
Upload Medium 

### ISSUE THREAD

**Issue by rizz-electrical-engg** [Nubuki-all/Enc#23]
Hello I'm using this ENC  repo and I just wanna know how to change its uploading medium like DOC  to VIDEOS. Will you please help me .

**Comment by Nubuki-all** [comment]
I'll add an env variable to change uploading medium

**Comment by rizz-electrical-engg** [comment]
Thankyou 🌟

**Comment by Nubuki-all** [comment]
@rizz-electrical-engg 
All done.

**Comment by rizz-electrical-engg** [comment]
Thanyou so much 🌟
