### ISSUE TITLE
No Video Duration

### ISSUE THREAD

**Issue by Afam007** [Nubuki-all/Enc#26]
Uploaded videos display 0:00 as the duration , which is false , please fix this 
![Screenshot_20241129-163557_Telegram](https://github.com/user-attachments/assets/cbfadba6-6ab2-410a-a2b4-3da918610a38)

**Comment by Nubuki-all** [comment]
Yh, I just need to retrieve and pass duration

**Comment by Afam007** [comment]
> Yh, I just need to retrieve and pass duration

Do that with video width and height , though it's not necessary

**Comment by Nubuki-all** [comment]
> Do that with video width and height , though it's not necessary
Setting thumbnail should have already taken care of that

**Comment by Nubuki-all** [comment]
Can you check now?

**Comment by Afam007** [comment]
It shows now, thank you
