### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by krackxor** [Nubuki-all/Enc#29]
Can you add a button feature without requiring FFmpeg code, supporting group usage with commands similar to VideoFlux-Re repository 

https://github.com/sahilgit55/VideoFlux-Re

**Comment by Nubuki-all** [comment]
Should be doable 
But I don't wanna

**Comment by Nubuki-all** [comment]
Making the bot usable in groups for multiple users is not a priority for me atm

**Comment by krackxor** [comment]
Ok sir, thank you for your feedback
